var settings = {
  "entry_time": 150,
  "cook_time": 60.0,
  "cooldown_time": 300.0,
  "steal_amount": 12,
  "steal_chance": 35.0,
  "sabotage_amount": 12,
  "sabotage_chance": 70.0,
  "anomoly_chance": 10.0,
  "anomoly_chance_breakdown": 10.0,
  "anomoly_chance_flop": 60.0,
  "anomoly_chance_flop_lower_bound": 40.0,
  "anomoly_chance_flop_upper_bound": 60.0,
  "anomoly_chance_oven_fail": 30.0,
  "anomoly_chance_oven_fail_lower_bound": 20.0,
  "anomoly_chance_oven_fail_upper_bound": 40.0,
  "tick_refresh_rate": 5.0,
  "first_place_multiplier": "2",
  "second_place_multiplier": "1.75",
  "third_place_multiplier": "1.5",
  "general_place_multiplier": "1.25",
  "general_multiplier": "1.25",
  "steal_max_count": 3,
  "sabotage_max_count": 3
};